name : CI Tourguide
on : [ push, pull_request ]

jobs :
  build :
    name : Build
    runs-on : ubuntu-latest
    #    container :
    #      image : maven
    steps :
      #      - name: Set up everything
      #        uses: s4u/setup-maven-action@v1.14.0
      #        with :
      #          java-version : 19
      #          maven-version : 3.8.7
      - name : Get code
        uses : actions/checkout@v4

      - name : Set up JDK 19
        uses : actions/setup-java@v4.4.0
        with :
          distribution : 'temurin'
          java-version : '19'
          cache : maven

      - name : Set up Maven
        uses : stCarolas/setup-maven@v5
        with :
          maven-version : 3.8.7

      - name : Install manual dependencies
        run : |
          echo pwd
          mvn install:install-file -Dfile="./libs/gpsUtil.jar" -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion="1.0.0" -Dpackaging=jar -DgeneratePom=true
          mvn install:install-file -Dfile="./libs/RewardCentral.jar" -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion="1.0.0" -Dpackaging=jar -DgeneratePom=true
          mvn install:install-file -Dfile="./libs/TripPricer.jar" -DgroupId=tripPricer -DartifactId=tripPricer -Dversion="1.0.0" -Dpackaging=jar -DgeneratePom=true

      - name : Cache dependencies
        uses : actions/cache@v4.0.2
        with :
          path : ~/.m2/repository
          key : ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name : Build Tourguide
        run : mvn clean install -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.1
        with :
          name : tourguide-jar
          path : target/*.jar


  unit-tests :
    name : Unit Tests
    runs-on : ubuntu-latest
    steps :
      - name : Get code
        uses : actions/checkout@v4

      - name : Set up JDK 19
        uses : actions/setup-java@v4.4.0
        with :
          distribution : 'temurin'
          java-version : '19'

      - name : Set up Maven
        uses : stCarolas/setup-maven@v5
        with :
          maven-version : 3.8.7

      - name : Install manual dependencies
        run : |
          echo pwd
          mvn install:install-file -Dfile="./libs/gpsUtil.jar" -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion="1.0.0" -Dpackaging=jar -DgeneratePom=true
          mvn install:install-file -Dfile="./libs/RewardCentral.jar" -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion="1.0.0" -Dpackaging=jar -DgeneratePom=true
          mvn install:install-file -Dfile="./libs/TripPricer.jar" -DgroupId=tripPricer -DartifactId=tripPricer -Dversion="1.0.0" -Dpackaging=jar -DgeneratePom=true

      - name : Cache dependencies
        uses : actions/cache@v4.0.2
        with :
          path : ~/.m2/repository
          key : ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name : Test Tourguide (unit)
        run : mvn clean test -Punit-tests

  performance-tests :
    name : Performance Tests
    runs-on : ubuntu-latest
    steps :
      - name : Get code
        uses : actions/checkout@v4

      - name : Set up JDK 19
        uses : actions/setup-java@v4.4.0
        with :
          distribution : 'temurin'
          java-version : '19'

      - name : Set up Maven
        uses : stCarolas/setup-maven@v5
        with :
          maven-version : 3.8.7

      - name : Install manual dependencies
        run : |
          echo pwd
          mvn install:install-file -Dfile="./libs/gpsUtil.jar" -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion="1.0.0" -Dpackaging=jar -DgeneratePom=true
          mvn install:install-file -Dfile="./libs/RewardCentral.jar" -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion="1.0.0" -Dpackaging=jar -DgeneratePom=true
          mvn install:install-file -Dfile="./libs/TripPricer.jar" -DgroupId=tripPricer -DartifactId=tripPricer -Dversion="1.0.0" -Dpackaging=jar -DgeneratePom=true

      - name : Cache dependencies
        uses : actions/cache@v4.0.2
        with :
          path : ~/.m2/repository
          key : ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name : Test Tourguide (performances)
        run : mvn clean test -Pperformance-tests

  release :
    name : Release
    needs : build
    runs-on : ubuntu-latest
    steps :
      - name : Get code
        uses : actions/checkout@v4

      #      - name : Check if master
      #        id : check_branch
      #        run : |
      #            if [ "${{ github.ref }}" != "refs/heads/master" ]; then
      #              echo "Not on master branch, skipping release."
      #              exit 0
      #            fi

      - name : Download artifact
        uses : actions/download-artifact@v4.1.8
        with :
          name : tourguide-jar
        run : ls -la

      - name : Extract version from pom.xml
        id : extract_version
        run : |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Project version: $VERSION"
          echo "::set-output name=VERSION::$VERSION"
          ls -la


      - name : Create GitHub Release
        uses : ncipollo/release-action@v1.14.0
        with :
          tag : ${{ steps.extract_version.outputs.VERSION }}
          name : 'Release ${{ steps.extract_version.outputs.VERSION }}'
          draft : false
          prerelease : false
          artifacts : '*.jar'