name : Release Tourguide
on:
  push:
    tags:
      - '*.*.*'

jobs :
  build :
    name: Build
    runs-on : ubuntu-latest
    steps :
      - name : Get code
        uses : actions/checkout@master

      - name : Set up JDK 19
        uses : actions/setup-java@v4.4.0
        with :
          distribution : 'temurin'
          java-version : '19'

      - name : Set up Maven
        uses : stCarolas/setup-maven@v5
        with :
          maven-version : 3.8.7

      - name : Install manual dependencies
        run : |
          echo pwd
          mvn install:install-file -Dfile="./libs/gpsUtil.jar" -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion="1.0.0" -Dpackaging=jar -DgeneratePom=true
          mvn install:install-file -Dfile="./libs/RewardCentral.jar" -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion="1.0.0" -Dpackaging=jar -DgeneratePom=true
          mvn install:install-file -Dfile="./libs/TripPricer.jar" -DgroupId=tripPricer -DartifactId=tripPricer -Dversion="1.0.0" -Dpackaging=jar -DgeneratePom=true

      - name : Cache dependencies
        uses : actions/cache@v4.0.2
        with :
          path : ~/.m2/repository
          key : ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name : Build Tourguide
        run : mvn clean site -DskipTests

      - name : Copy artifact
        run : mkdir release && cp target/*.jar release

      - name : Create Release
        uses : ncipollo/release-action@v1.14.0
        with :
          artifacts : "release/*.jar"

